name: Booking Manager Deploy
on:
    push:
        branches:
            - 'feature/docker'

permissions:
    id-token: write 
              
jobs:
    buildandpush:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                role-to-assume: arn:aws:iam::058264348381:role/CheLagarto-ECR-Role
                aws-region: us-east-1

            - name: Setup AWS CLI
              run: |
                    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    unzip -qq awscliv2.zip
                    sudo ./aws/install

            - name: Build and Push to ECR
              run: |
                docker build -t booking-manager .
                docker tag booking-manager:latest 058264348381.dkr.ecr.us-east-1.amazonaws.com/booking-manager:latest
                docker push 058264348381.dkr.ecr.us-east-1.amazonaws.com/booking-manager:latest